import type { Metadata } from "next";
import { Geist, Geist_Mono, } from "next/font/google";
import "./globals.css";
import NavbarAdmin from "@/components/navbarAdmin";
import { ToastProvider } from "@/hooks/use-toast";
import { AuthProvider } from '@/hooks/useAuth'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "sistema sird",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <style>{`
html {
  font-family: ${geistSans.style.fontFamily};
  --font-sans: ${geistSans.variable};
  --font-mono: ${geistMono.variable};
}
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen bg-white`}
      >
        <AuthProvider>
          <NavbarAdmin />
          <main className="w-screen text-center bg-gray-100 overflow-auto">
            <ToastProvider>
              {children}
            </ToastProvider>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
