import { MigrationInterface, QueryRunner } from 'typeorm';

export class DropTurnoIdFromGrupos20260627000100 implements MigrationInterface {
  name = 'DropTurnoIdFromGrupos20260627000100';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Drop FK constraint if exists (autogenerated by TypeORM)
    await queryRunner.query(`
      do $$
      declare
        fk_name text;
      begin
        select con.conname into fk_name
        from pg_catalog.pg_constraint con
        join pg_catalog.pg_class rel on rel.oid = con.conrelid
        join pg_catalog.pg_namespace nsp on nsp.oid = rel.relnamespace
        join pg_catalog.pg_attribute a on a.attrelid = con.conrelid and a.attnum = any(con.conkey)
        where nsp.nspname = 'organizacion_escolar'
          and rel.relname = 'grupos'
          and con.contype = 'f'
          and a.attname = 'turnoId';

        if fk_name is not null then
          execute format('alter table organizacion_escolar.grupos drop constraint %I', fk_name);
        end if;
      end;
      $$;
    `);

    // 2. Drop the column (created by TypeORM as turnoId camelCase)
    await queryRunner.query(`
      alter table organizacion_escolar.grupos drop column if exists "turnoId";
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Restore the column
    await queryRunner.query(`
      alter table organizacion_escolar.grupos add column "turnoId" int2 null;
    `);

    // Add FK constraint back
    await queryRunner.query(`
      alter table organizacion_escolar.grupos
        add constraint fk_grupos_turno_id
        foreign key ("turnoId") references catalogos.turno(id)
        on delete cascade;
    `);
  }
}
